CA=1

NODETEST = at_areaInFocusTest.js at_coselectableTest.js \
	at_reorderableTest.js at_snappableTest.js \
	at_b1082EvaluationNodeActivationTest.js

ROOTDIR=../../..
CDLDIR=../..
CUSTOMERDATADIR = ../../template/data
CUSTOMERDIR = ../

COMPJSDEP = ../func/*.js ../design/*.js ../includeList.js

include $(ROOTDIR)/util/mmk
