JS_SOURCES= myLeanZCApp.js ETFScreener.js stockScreener.js MBAScreener.js \
	lendingClubScreener.js exportHistogram.js

ROOTDIR=../../../..
CDLDIR=../../..
DATADIR = ../../template/data

COMPJSDEP = ../func/*.js ../design/*.js ../includeList.js ../../../core/func/*.js ../../../core/design/*.js ../../../core/includeList.js

include $(ROOTDIR)/lang/util/mmk
