// Copyright 2017 Yoav Seginer, Theo Vosse, Gil Harari, and Uri Kolodny.
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

var quandlSF1Schema = {
    /////////////////////////////////////////////////////////////////////////////////////////////////////////
    // This class provides the initial ordering and expansion state of the facets in the app.
    /////////////////////////////////////////////////////////////////////////////////////////////////////////
    AppSchema: {
        "class": "QuandlSF1AppSchema",
        context: {
            // this defines the initial ordering of facets and their
            //   expansion state.       
            dataSourceFacetDataOrdering: o(
                { uniqueID: "ticker" },
                { uniqueID: "Name" },
                { uniqueID: "Sector" },
                { uniqueID: "Industry" },
                { uniqueID: "Exchange" },
                { uniqueID: "mrqdate" },
                { uniqueID: "mrydate" },
                { uniqueID: "FILINGDATE" },
                //{ uniqueID: "FILINGTYPE" },
                // { uniqueID: "EVENT" }, 
                { uniqueID: "INVENTORY_MRQ" },
                { uniqueID: "RETEARN_MRQ" },
                { uniqueID: "NCFCOMMON_MRQ" },
                { uniqueID: "NCFCOMMON_MRT" },
                { uniqueID: "NCFCOMMON_MRY" },
                { uniqueID: "NCFDEBT_MRQ" },
                { uniqueID: "NCFDEBT_MRT" },
                { uniqueID: "NCFDEBT_MRY" },
                { uniqueID: "NCFDIV_MRQ" },
                { uniqueID: "NCFDIV_MRT" },
                { uniqueID: "NCFDIV_MRY" },
                { uniqueID: "NCFDIV_MRY" },
                { uniqueID: "ACCOCI_MRQ" },
                { uniqueID: "ASSETSAVG_MRT" },
                { uniqueID: "ASSETSC_MRQ" },
                { uniqueID: "ASSETSNC_MRQ" },
                { uniqueID: "ASSETS_MRQ" },
                { uniqueID: "ASSETTURNOVER_MRT" },
                { uniqueID: "BVPS_MRQ" },
                { uniqueID: "CAPEX_MRQ" },
                { uniqueID: "CAPEX_MRY" },
                { uniqueID: "CASHNEQ_MRQ" },
                { uniqueID: "COR_MRQ" },
                { uniqueID: "COR_MRT" },
                { uniqueID: "COR_MRY" },
                { uniqueID: "CURRENTRATIO_MRQ" },
                { uniqueID: "DEBT_MRQ" },
                { uniqueID: "DEPAMOR_MRQ" },
                { uniqueID: "DEPAMOR_MRT" },
                { uniqueID: "DEPAMOR_MRY" },
                { uniqueID: "DE_MRQ" },
                { uniqueID: "DILUTIONRATIO_MRQ" },
                { uniqueID: "DILUTIONRATIO_MRT" },
                { uniqueID: "DILUTIONRATIO_MRY" },
                { uniqueID: "DIVYIELD" },
                { uniqueID: "DPS_MRQ" },
                { uniqueID: "DPS_MRT" },
                { uniqueID: "DPS_MRY" },
                { uniqueID: "EBITDAMARGIN_MRT" },
                { uniqueID: "EBITDA_MRQ" },
                { uniqueID: "EBITDA_MRT" },
                { uniqueID: "EBITDA_MRY" },
                { uniqueID: "EBIT_MRQ" },
                { uniqueID: "EBIT_MRT" },
                { uniqueID: "EBIT_MRY" },
                { uniqueID: "EBT_MRQ" },
                { uniqueID: "EBT_MRT" },
                { uniqueID: "EBT_MRY" },
                { uniqueID: "EPSDILGROWTH1YR_MRT" },
                { uniqueID: "EPSDIL_MRQ" },
                { uniqueID: "EPSDIL_MRT" },
                { uniqueID: "EPSDIL_MRY" },
                { uniqueID: "EPSGROWTH1YR_MRT" },
                { uniqueID: "EPS_MRQ" },
                { uniqueID: "EPS_MRT" },
                { uniqueID: "EPS_MRY" },
                { uniqueID: "EQUITYAVG_MRT" },
                { uniqueID: "EQUITY_MRQ" },
                { uniqueID: "EV" },
                { uniqueID: "EVEBITDA_MRT" },
                { uniqueID: "EVEBIT_MRT" },
                { uniqueID: "FCFPS_MRQ" },
                { uniqueID: "FCFPS_MRT" },
                { uniqueID: "FCFPS_MRY" },
                { uniqueID: "FCF_MRQ" },
                { uniqueID: "FCF_MRT" },
                { uniqueID: "FCF_MRY" },
                { uniqueID: "GP_MRQ" },
                { uniqueID: "GP_MRT" },
                { uniqueID: "GP_MRY" },
                { uniqueID: "GROSSMARGIN_MRT" },
                { uniqueID: "INTANGIBLES_MRQ" },
                { uniqueID: "INTERESTBURDEN_MRT" },
                { uniqueID: "INTEXP_MRQ" },
                { uniqueID: "INTEXP_MRT" },
                { uniqueID: "INTEXP_MRY" },
                { uniqueID: "LEVERAGERATIO_MRT" },
                { uniqueID: "LIABILITIESC_MRQ" },
                { uniqueID: "LIABILITIESNC_MRQ" },
                { uniqueID: "LIABILITIES_MRQ" },
                { uniqueID: "MARKETCAP" },
                { uniqueID: "NCFF_MRQ" },
                { uniqueID: "NCFF_MRT" },
                { uniqueID: "NCFF_MRY" },
                { uniqueID: "NCFI_MRQ" },
                { uniqueID: "NCFI_MRT" },
                { uniqueID: "NCFI_MRY" },
                { uniqueID: "NCFOGROWTH1YR_MRT" },
                { uniqueID: "NCFO_MRQ" },
                { uniqueID: "NCFO_MRT" },
                { uniqueID: "NCFO_MRY" },
                { uniqueID: "NCFX_MRQ" },
                { uniqueID: "NCFX_MRT" },
                { uniqueID: "NCFX_MRY" },
                { uniqueID: "NCF_MRQ" },
                { uniqueID: "NCF_MRT" },
                { uniqueID: "NCF_MRY" },
                { uniqueID: "NETINCCMN_MRQ" },
                { uniqueID: "NETINCCMN_MRT" },
                { uniqueID: "NETINCCMN_MRY" },
                { uniqueID: "NETINCDIS_MRQ" },
                { uniqueID: "NETINCDIS_MRT" },
                { uniqueID: "NETINCDIS_MRY" },
                { uniqueID: "NETINCGROWTH1YR_MRT" },
                { uniqueID: "NETINC_MRQ" },
                { uniqueID: "NETINC_MRT" },
                { uniqueID: "NETINC_MRY" },
                { uniqueID: "NETMARGIN_MRT" },
                { uniqueID: "PAYABLES_MRQ" },
                { uniqueID: "PAYOUTRATIO_MRT" },
                { uniqueID: "PB_MRQ" },
                { uniqueID: "PE1_MRT" },
                { uniqueID: "PE_MRT" },
                { uniqueID: "PREFDIVIS_MRQ" },
                { uniqueID: "PREFDIVIS_MRT" },
                { uniqueID: "PREFDIVIS_MRY" },
                { uniqueID: "PRICE" },
                { uniqueID: "PS1_MRT" },
                { uniqueID: "PS_MRT" },
                { uniqueID: "RECEIVABLES_MRQ" },
                { uniqueID: "REVENUEGROWTH1YR_MRT" },
                { uniqueID: "REVENUE_MRQ" },
                { uniqueID: "REVENUE_MRT" },
                { uniqueID: "REVENUE_MRY" },
                { uniqueID: "RND_MRQ" },
                { uniqueID: "RND_MRT" },
                { uniqueID: "RND_MRY" },
                { uniqueID: "ROA_MRT" },
                { uniqueID: "ROE_MRT" },
                { uniqueID: "ROS_MRT" },
                { uniqueID: "SGNA_MRQ" },
                { uniqueID: "SGNA_MRT" },
                { uniqueID: "SGNA_MRY" },
                //{ uniqueID: "SHAREFACTOR" },
                { uniqueID: "SHARESBAS" },
                { uniqueID: "SHARESWADIL_MRQ" },
                { uniqueID: "SHARESWADIL_MRT" },
                { uniqueID: "SHARESWADIL_MRY" },
                { uniqueID: "SHARESWAGROWTH1YR_MRT" },
                { uniqueID: "SHARESWA_MRQ" },
                { uniqueID: "SHARESWA_MRT" },
                { uniqueID: "SHARESWA_MRY" },
                { uniqueID: "SPS_MRT" },
                { uniqueID: "TANGIBLES_MRQ" },
                { uniqueID: "TAXEFFICIENCY_MRT" },
                { uniqueID: "TAXEXP_MRQ" },
                { uniqueID: "TAXEXP_MRT" },
                { uniqueID: "TAXEXP_MRY" },
                { uniqueID: "TBVPS_MRQ" },
                { uniqueID: "WORKINGCAPITAL_MRQ" },
                o()
            )
        }
    }
};
