JS_SOURCES= myLeanFSApp.js myFatFSApp.js myFSApp.js \
    rectangularNecklaceTest.js stayOffTheLawnTest.js \
    reflectionTest.js wrapAroundTest.js checkers.js \
    areaInFocusTest.js dragTest.js stockAndFlowTest.js snappableTest.js \
    contMovableTest.js reorderableTest.js expandableTest.js \
    coselectableTest.js writableRefTest.js portfolioTest.js expireCounter.js \
    displayQueryTest.js radioButtonTest.js calculatorTest.js udfTest.js matrix.js saveViewTest.js contentFrameTest.js

ROOTDIR=../../..
CDLDIR=../..
CUSTOMERDATADIR = ../../template/data
CUSTOMERDIR = ../

COMPJSDEP = ../func/*.js ../design/*.js ../includeList.js

include $(ROOTDIR)/lang/util/mmk
