CA=1

AUTOMATEDTESTING = true

NODETEST = at_myLeanFSApp.js at_myFatFSApp.js at_myLeanSF1App.js

ROOTDIR=../../../..
CDLDIR=../../..
DATADIR = ../../template/data

COMPJSDEP = ../func/*.js ../design/*.js ../includeList.js ../../../core/func/*.js ../../../core/design/*.js ../../../core/includeList.js

include $(ROOTDIR)/lang/util/mmk
